---
# Ref: https://www.bengreenberg.dev/posts/2023-04-09-github-profile-dynamic-content/
name: Update Recent Blog Posts

on:
  schedule:
    - cron: '0 0 * * 0'  # Run once a week at 00:00 (midnight) on Sunday
  workflow_dispatch:

jobs:
  updateReadmeWithRecentPosts:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: gem install httparty nokogiri octokit

      - name: Scrape posts and update README
        run: ruby ./.github/scripts/update_posts.rb
